#!/usr/bin/env perl

use Mojolicious::Lite;

use constant DEBUG => 0;

my $vibramail = "default\@colectivovibracion.org";
my @mail = qw(msmtp -a vibracion -t);
DEBUG && push @mail, qw(-v); # log email transaction

# receives an email as argument, sends it to recipients in its content, returns
# false if everything is ok, returns error code otherwise.
helper sendmail => sub {
	my $self = shift;
        my $content = shift;
        my $mailfd;

        DEBUG && warn "DEBUG: $content";
        return 0 unless $content;
        open $mailfd, "|-", @mail or $self->app->log->fatal("cannot run @mail: $!");

        print $mailfd $content or $self->app->log->fatal("cannot print into mailfd: $!");
        return 0 if close $mailfd;
	if ($! == 0) { # exit() with non-zero status
		$self->app->log->error("@mail returned non-zero status.");
		return $? >> 8;
	} elsif ($!) {
		$self->app->log->warn("cannot close mailfd: $!");
		return -1;
	}

        return 0;

};

get "/" => "index";
get "/contacto" => "contacto";
get "/convocatoria" => "convocatoria";
get "/registro" => "registro";

# check form params, validate them, if ok generate an email body, send it
# to the autor, then generate everything is ok page, otherwise: generate a page
# showing bad params
post "/registro" => sub {
	my $self = shift;
	my @param = $self->param;
	my %valid;
	my %invalid; # (invalid fieldname => "reason of invalidness")
	my $mail;
	my $error = "";

	%valid = %invalid = map {($_, undef)} @param;
	for (@param) {
		my $val = $self->param($_);
		if ($_ eq "eventdur") {
			$valid{$_} = $val if
			    $val =~ /^[0-9]{1,2}:[0-9]{1,2}$/;
		} elsif ($_ eq "autorcol") {
			$valid{$_} = $val if $val =~ /^$|^.*$/;
		} elsif ($_ eq "autormail") {
			$valid{$_} = $val if $val =~ /^[^@]+@[A-za-z0-9.-]+$/;
		} elsif ($_ eq "autortel") {
			$valid{$_} = $val if $val =~ /^$|^[0-9]+$/;
		} elsif ($_ eq "eventtm") {
			$valid{$_} = $val if
			    $val eq "" or $val =~ /^[0-9]{1,2}:[0-9]{1,2}$/;
		} elsif ($_ eq "eventna") {
			$valid{$_} = $val if $val ne "" and length($val) < 32;
		} elsif ($_ eq "eventsubna") {
			$valid{$_} = $val if $val ne "" and length($val) < 32;
		} else { # simple not emptyness evaluation for other fields
			$valid{$_} = $val if $val ne "";
		}
	}
	$self->app->log->debug("valid: ",
	    join(", ", map {defined $valid{$_} ?  "$_: $valid{$_}" : "$_: undef"}  sort keys %valid));
	$self->stash(valid => \%valid);
	$self->stash(ispost => 1);
	goto render if grep {not defined $_} values %valid; # any param error

	$error .= "No se pudo generar el correo. ", goto render if
	    not $mail = $self->render("registro/mail", format => 'txt', partial => 1);
	$error .= "No se pudo enviar el correo. ", goto render if
	    $self->sendmail($mail) != 0;


	render:

	$self->app->log->debug("error: $error");
	return $self->render("registro", format => "html", error => $error);
} => "registro";

app->config(hypnotoad => {listen => ["http://*:3000/"], proxy => 1});
app->start;
